// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfirdtszlyefspbbhrzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmaXJkdHN6bHllZnNwYmJocnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDk1MTksImV4cCI6MjA3NDM4NTUxOX0.ZSEZVLlcsJ6xcOROEmE8pPRVkgI0NwvXYmaqTP88eEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});